### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by IanDelMar**
## Description
This PR 
* adds/updates a couple of translations.
* removes translations which are handled via [WP's language packs for Understrap](https://translate.wordpress.org/projects/wp-themes/understrap/language-packs/). 
The translations were mostly taken from the core and default theme translations.

Changes in source strings:
* Switch from "Choose between Bootstrap 4 _or_ Bootstrap 5" to "Choose between Bootstrap 4 _and_ Bootstrap 5"

## Motivation and Context
Add missing translations.

### Before PR
image

### After PR
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I pulled my branch from `develop`.
- [x] I am submitting my pull request to `develop`.
- [x] I have resolved any conflicts merging this pull request would create.
- [x] I have checked that there aren't other open Pull Requests for the same update/change.
- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] \(Optional) My change requires a change to the translations.
- [x] \(Optional) I have updated the translations accordingly.
- [x] I have read the **[CONTRIBUTING](https://github.com/understrap/understrap/blob/main/.github/CONTRIBUTING.md)** document.

### CODE REVIEW

**Comment by IanDelMar** [comment]
I added the German translations via the [Translating WordPress Page](https://translate.wordpress.org/)https://translate.wordpress.org/projects/wp-themes/understrap/). @bacoords can you request a review?

**Comment by IanDelMar** [comment]
Language pack for Dutch (Belgium) now available.

**Comment by IanDelMar** [comment]
Language pack for Czech now available.

**Comment by IanDelMar** [comment]
[Language pack](https://translate.wordpress.org/projects/wp-themes/understrap/language-packs/) for Romanian now available.

**Comment by IanDelMar** [comment]
[Language pack](https://translate.wordpress.org/projects/wp-themes/understrap/language-packs/) for Galician and Dutch (formal) now available.

**Comment by IanDelMar** [comment]
[Language pack](https://translate.wordpress.org/projects/wp-themes/understrap/language-packs/) for Norwegian (Bokmål) available.

**Comment by IanDelMar** [comment]
[Language pack](https://translate.wordpress.org/projects/wp-themes/understrap/language-packs/) for Greek available.

**Comment by IanDelMar** [comment]
[Language pack](https://translate.wordpress.org/projects/wp-themes/understrap/language-packs/) for Slovak available.

**Review by bacoords — APPROVED** [review]

**Pull request merged**
