### PR TITLE
Revise markup for navbar toggle.

### PR DESCRIPTION
**Pull request by tedgeving**
1. Current BS4 documentation uses an entity for the navbar toggle instead of styled span tags.

2. Change navbar toggle class to match documentation. 

http://v4-alpha.getbootstrap.com/components/navbar/

### CODE REVIEW

**Comment by maxdmyers** [comment]
Just curious, why was this closed & deleted? This is the method used on the bootstrap docs and works well.

**Comment by tedgeving** [comment]
Good question @maxdmyers,
I closed it because I was not sure about the correct process for submitting pull requests to the project.  

It looks like the existing navbar is using BS3 markup, the header should be updated.
https://github.com/holger1411/understrap/blob/master/header.php#L42

I'm happy to reopen it, let me know.

**Comment by maxdmyers** [comment]
Please do, I found this PR to be valid and useful. If the theme is using B4, it should be fully embracing B4 markup.

**Comment by tedgeving** [comment]
Please update the navbar to use BS4 markup.

**Comment by holger1411** [comment]
I also add the hidden-sm-up class to reproduce the BS3 behavior. The hamburger icon will appear/work on smaller screens only.

**Comment by holger1411** [comment]
+1 @tedgeving

**Pull request merged**
