### PR TITLE
README Improvements

### PR DESCRIPTION
**Pull request by kylemorgan49**
I made some improvements to the README. These changes may seem minor to the progression of the project, but hey, somebody has to do this stuff.

1. I went through and fixed some of the broken English.
2. I went through and fixed some of the typography (things like proper quotes, proper usage of dashes and hyphens, proper ellipsis, and proper arrows). The importance of that is debatable, but hey, there you go.
3. I standardized the header markdown. You were mixing markdown syntax, so I changed all the syntax to the syntax suggested [here](https://help.github.com/articles/basic-writing-and-formatting-syntax/).
4. I standardized the capitalization in the headers. You were mixing capitalization, so I ran all your headers through [this tool](http://titlecapitalization.com/).

### CODE REVIEW

**Comment by holger1411** [comment]
Big thx @kylemorgan49! 
I´am not a native english speaker ... and sometimes a readme seems to be "not-so-important".
But it is the main part of a users first impression of a project...so I definitely appriciate your work!

**Comment by kylemorgan49** [comment]
Why was this reverted, @holger1411?

**Comment by kylemorgan49** [comment]
Oh shit, I just realized what I did. I made the fixes I wanted you to merge, then I sent the pull request. But then after that, I was making changes for myself that I never wanted in the project, and you accidentally merged those changes in too. Crap. Sorry about that.

**Comment by kylemorgan49** [comment]
Here’s what I want to happen, and I don’t quite know how the whole fork/merge thing works. I want the README changes to be made, but I also wanted to fork this project so that I can build something of my own (that will never be merged back into your project). How can we solve this?

**Comment by Thomas-A-Reinert** [comment]
Stuff happens, same here. Git/hub ain´t to intuitive sometimes. ;)
In the main listing there should be a "fork" button. No matter in which. So just fork it into a new project. That should do the job..

**Comment by dvlopes** [comment]
I'm afraid you can't do that.
I've tried to fork my own project, or fork understrap project twice in my own account and github doesn't allowed me to.

**Comment by kylemorgan49** [comment]
Yeah, GitHub will only let me have one fork of UnderStrap. The only way I see doing this is for me to copy all the files into a new repo and push it to GitHub. Then I can revert the forked one back to the way I wanted it in the pull request, and open up a new pull request.

**Comment by Thomas-A-Reinert** [comment]
Oh, sorry. Tried before - but under different circumstances it seems. Really sorry for any misleading info!

**Comment by holger1411** [comment]
@kylemorgan49: Yep, I reverted to your last commit to the right readme version. So your changes *should* be in.

@all: thx for supporting @kylemorgan49

**Comment by holger1411** [comment]
Oh, and it might be the best to work with branches. Having one original master branch and another with your own changes. So you can merge from one into another (if needed) while keeping the original master branch.

**Comment by kylemorgan49** [comment]
@holger1411: The changes aren’t in the README. Should I change my repo back to the correct version and open a new pull request?

**Comment by holger1411** [comment]
Yep, would be great

**Pull request merged**
