### PR TITLE
Automatic code style checking

### PR DESCRIPTION
**Pull request by carl-alberto**
https://github.com/holger1411/understrap/issues/231

### CODE REVIEW

**Comment by holger1411** [comment]
Thx for your contribution!
The bootstrap-wp-gallery file was not used anymore...but still in the package.
I removed it

**Comment by carl-alberto** [comment]
Nice but unfortunately it seems we have a lot to fix in the code level to conform with the WP standards, Please see this log on the files that needs fixes: https://travis-ci.org/carl-alberto/understrap/jobs/195623743

**Comment by holger1411** [comment]
Yeah, a lot of work.
But its good to know where and what is wrong.
Will beginn to go through the problems, file-by-file.

**Comment by holger1411** [comment]
Hm, but i´am not sure if anything is an error.
For example:
```
FILE: /home/travis/build/carl-alberto/understrap/404.php

----------------------------------------------------------------------

FOUND 3 ERRORS AFFECTING 3 LINES

----------------------------------------------------------------------

 24 | ERROR | Expected next thing to be an escaping function (like

    |       | esc_html_e() or esc_attr_e()), not '_e'
```

Even _underscores and Twenty Seventeen use the same "_e" function in there 404.php file for the same purpose/text.

**Comment by holger1411** [comment]
Oh, and it says:
PHPCBF CAN FIX THE X MARKED SNIFF VIOLATIONS AUTOMATICALLY
I have no idea how PHPCBF works, but autofixing of 50%+ of all issues sounds nice.

@carl-alberto Can you help with that?

**Comment by carl-alberto** [comment]
Instructions on how to setup phpcbf is in here https://github.com/squizlabs/PHP_CodeSniffer

You might have branched it an old version of _S that is why it is throwing a lot of errors? We might need to update a lot of the codebase if that is the case :(

But are you open to collaborating with a project where we have an underscore "like" theme builder like this site? https://underscores.me/  That might be a good chance for us to rewrite your whole theme with the latest codebase of _S. but plus the option to add components like bootstrap, js slider, google fonts, etc ? I'm planning to start one this mid-Feb ? :)

**Comment by holger1411** [comment]
Argh.  :flushed: 
I just typed in "underscores" as search term here on Github and found this:
https://github.com/Automattic/underscores.me/blob/master/404.php
So thats the underscores websites repo...not underscores itself.

To your second question:
Yes, I am open for collaboration.
But UnderStrap is developed within my rare spare time outside my fulltime job (UX and fontend dev...so I´am not a PHP guru;-). And its the same (as far as I know) with other collaborators here.
So I can´t gurantee that I am able to put a certain amout of work into it till a certain date to archive certain milestones.

But, of course,  you are welcome to support UnderStrap and to use it for other projects like a dynamic theme builder website. And I´am open for feedback on how to improve it.

**Pull request merged**
